### PR TITLE
Fix some issues in a test case

### LINKED ISSUE #20: Test test_pid_check_samepid_two_processes fails on FreeBSD
If I understand this error correctly, the code did not raise a `PidFileAlreadyRunningError` when it was supposed to. I do not yet know why.

I have no problem running the test suite on Linux (Python 3.7.1), only on FreeBSD (Python 3.6.6).

```
======================================================================
FAIL: test_pid.test_pid_check_samepid_two_processes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/ports/devel/py-pid/work-py36/pid-2.2.1/tests/test_pid.py", line 280, in test_pid_check_samepid_two_processes
    pidfile_proc2.create()
  File "/usr/local/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/usr/ports/devel/py-pid/work-py36/pid-2.2.1/tests/test_pid.py", line 42, in raising
    raise AssertionError("Failed to throw exception of type(s) %s." % (", ".join(exc_type.__name__ for exc_type in exc_types),))
AssertionError: Failed to throw exception of type(s) PidFileAlreadyRunningError, PidFileAlreadyLockedError.
-------------------- >> begin captured logging << --------------------
PidFile: DEBUG: <pid.PidFile object at 0x807eee2c8> entering setup
PidFile: DEBUG: <pid.PidFile object at 0x807eee2c8> create pidfile: /tmp/setup.py.pid
PidFile: DEBUG: <pid.PidFile object at 0x807eee2c8> check pidfile: /tmp/setup.py.pid
PidFile: DEBUG: <pid.PidFile object at 0x807eee368> entering setup
PidFile: DEBUG: <pid.PidFile object at 0x807eee368> create pidfile: /tmp/setup.py.pid
PidFile: DEBUG: <pid.PidFile object at 0x807eee368> check pidfile: /tmp/setup.py.pid
PidFile: DEBUG: <pid.PidFile object at 0x807eee2c8> closing pidfile: /tmp/setup.py.pid
PidFile: DEBUG: <pid.PidFile object at 0x807eee368> closing pidfile: /tmp/setup.py.pid
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 32 tests in 0.030s

FAILED (failures=1)
Test failed: <unittest.runner.TextTestResult run=32 errors=0 failures=1>
error: Test failed: <unittest.runner.TextTestResult run=32 errors=0 failures=1>
```

Also, on [line 279](https://github.com/trbs/pid/blob/0efff53af4554dfc8e06a2627809baa84d13b732/tests/test_pid.py#L279), I don't understand why it is expecting `PidFileAlreadyLockedError`? If I remove it, so it only expects `PidFileAlreadyRunningError`, the test still passes (on Linux). So, what exactly is supposed be happening in this test case?

### PR DESCRIPTION
**Pull request by thnee**
Fixes #20 

Tested it on Linux, FreeBSD native, and FreeBSD jail, works as expected.

### CODE REVIEW

**Comment by thnee** [comment]
The tests are failing because of something unrelated. It has problems download python source from AWS S3. I don't think I can restart the job, since it is not my repo. Can you maybe restart it @trbs?

**Comment by thnee** [comment]
Hmm, maybe not optimal that I am decreasing the test coverage. Will look into that.

**Comment by thnee** [comment]
Thanks for the quick reactions! May I ask for a new release to pypi also? Since that is the master site used in the FreeBSD port.

**Comment by trbs** [comment]
@thnee  https://pypi.org/project/pid/2.2.2/ 🎉

**Comment by thnee** [comment]
Brilliant, thanks! :cake:

**Pull request merged**
